### ISSUE TITLE
compile_related_pairs throws an error if there are no related pairs

### ISSUE THREAD

**Issue by mskoldSU** [eriqande/CKMRpop#2]
Throws
```
Error in `colnames<-`(`*tmp*`, value = c("id_1", "id_2")) : 
  attempt to set 'colnames' on an object with less than two dimensions
```
rather than an empty tibble. Similar problem when `downsample_pairs` fails to sample a pair and passes an empty tibble to `relpair_conn_comps`.

**Comment by eriqande** [comment]
Hi Martin,
Thanks so much for pointing out this problem to me.  I made a few quick changes so that the functions just return a tibble of the expected shape (column names and types), but with 0 rows.  I've pushed that to GitHub and you should be able to get it with `remotes::install_github("eriqande/CKMRpop")`.  

Please let me know if you run into any other issues, etc.  Best regards,  eric
